version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/work
  web:
    build: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/work
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store:
